//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Admin
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Secondary_Email { get; set; }
        public string Country_Code { get; set; }
        public string Phone_Number { get; set; }
        public string Profile_Picture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
