//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Country_Code { get; set; }
        public string Phone_Number { get; set; }
        public string Profile_Picture { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Country { get; set; }
        public string University { get; set; }
        public string College { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Total_expenses { get; set; }
        public Nullable<int> Total_earnings { get; set; }
    
        public virtual User User { get; set; }
    }
}
